#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# RajutechieStreamKit - Development Environment Setup
# ─────────────────────────────────────────────────────────────────────────────
# Sets up a complete local development environment:
#   1. Verifies prerequisites (node, pnpm, docker, docker compose)
#   2. Installs monorepo dependencies
#   3. Copies .env.example if needed
#   4. Starts infrastructure dependencies (postgres, redis, kafka, mongo, minio)
#   5. Waits for all services to be healthy
#   6. Runs database migrations and seeds dev data
#   7. Prints helpful URLs and next steps
#
# Usage:  ./tools/scripts/setup-dev.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Colors & helpers ─────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; }
step()    { echo -e "\n${BOLD}${CYAN}==>${NC} ${BOLD}$*${NC}"; }

# ── Resolve project root ────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${PROJECT_ROOT}"

echo -e "\n${BOLD}${CYAN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${CYAN}║       RajutechieStreamKit - Dev Environment Setup       ║${NC}"
echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════════╝${NC}\n"

# ── Step 1: Check prerequisites ─────────────────────────────────────────────
step "Checking prerequisites"

MISSING=()

# Node.js >= 20
if command -v node &>/dev/null; then
  NODE_VERSION=$(node -v | sed 's/v//')
  NODE_MAJOR=$(echo "${NODE_VERSION}" | cut -d. -f1)
  if [ "${NODE_MAJOR}" -ge 20 ]; then
    success "Node.js ${NODE_VERSION}"
  else
    error "Node.js ${NODE_VERSION} found, but >= 20.0.0 is required"
    MISSING+=("node>=20")
  fi
else
  error "Node.js is not installed"
  MISSING+=("node")
fi

# pnpm >= 9
if command -v pnpm &>/dev/null; then
  PNPM_VERSION=$(pnpm -v)
  PNPM_MAJOR=$(echo "${PNPM_VERSION}" | cut -d. -f1)
  if [ "${PNPM_MAJOR}" -ge 9 ]; then
    success "pnpm ${PNPM_VERSION}"
  else
    error "pnpm ${PNPM_VERSION} found, but >= 9.0.0 is required"
    MISSING+=("pnpm>=9")
  fi
else
  error "pnpm is not installed (install: corepack enable && corepack prepare pnpm@9 --activate)"
  MISSING+=("pnpm")
fi

# Docker
if command -v docker &>/dev/null; then
  DOCKER_VERSION=$(docker --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
  success "Docker ${DOCKER_VERSION}"
else
  error "Docker is not installed (https://docs.docker.com/get-docker/)"
  MISSING+=("docker")
fi

# Docker Compose (v2 plugin)
if docker compose version &>/dev/null 2>&1; then
  COMPOSE_VERSION=$(docker compose version --short 2>/dev/null || echo "unknown")
  success "Docker Compose ${COMPOSE_VERSION}"
elif command -v docker-compose &>/dev/null; then
  COMPOSE_VERSION=$(docker-compose --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
  warn "docker-compose (standalone) ${COMPOSE_VERSION} - consider upgrading to Docker Compose v2"
else
  error "Docker Compose is not installed"
  MISSING+=("docker-compose")
fi

if [ ${#MISSING[@]} -gt 0 ]; then
  echo ""
  error "Missing prerequisites: ${MISSING[*]}"
  error "Please install the above tools and re-run this script."
  exit 1
fi

# ── Step 2: Install dependencies ────────────────────────────────────────────
step "Installing monorepo dependencies"

pnpm install
success "Dependencies installed"

# ── Step 3: Environment file ────────────────────────────────────────────────
step "Setting up environment files"

ENV_EXAMPLE="infrastructure/docker/.env.example"
ENV_FILE=".env"

if [ -f "${ENV_FILE}" ]; then
  info ".env already exists - skipping copy"
else
  if [ -f "${ENV_EXAMPLE}" ]; then
    cp "${ENV_EXAMPLE}" "${ENV_FILE}"
    success "Copied ${ENV_EXAMPLE} -> ${ENV_FILE}"
  else
    warn "No .env.example found - creating minimal .env"
    cat > "${ENV_FILE}" <<'ENVEOF'
# RajutechieStreamKit Development Environment
# Auto-generated by setup-dev.sh

# PostgreSQL
POSTGRES_USER=rajutechie-streamkit
POSTGRES_PASSWORD=rajutechie_streamkit_secret
POSTGRES_DB=rajutechie-streamkit
POSTGRES_PORT=5432

# MongoDB
MONGO_USER=rajutechie-streamkit
MONGO_PASSWORD=rajutechie_streamkit_secret
MONGO_DB=rajutechie-streamkit
MONGODB_PORT=27017

# Redis
REDIS_PASSWORD=rajutechie_streamkit_secret
REDIS_PORT=6379

# Kafka
KAFKA_PORT=9092

# MinIO (S3-compatible)
MINIO_ROOT_USER=rajutechie-streamkit
MINIO_ROOT_PASSWORD=rajutechie_streamkit_secret
MINIO_API_PORT=9000
MINIO_CONSOLE_PORT=9001

# JWT (development only - DO NOT use in production)
JWT_SECRET=dev_jwt_secret_rajutechie_streamkit_change_me
JWT_REFRESH_SECRET=dev_jwt_refresh_secret_rajutechie_streamkit_change_me

# Services
API_GATEWAY_PORT=3000
WS_GATEWAY_PORT=3001
AUTH_SERVICE_PORT=3010
USER_SERVICE_PORT=3011
CHAT_SERVICE_PORT=3012
CALL_SERVICE_PORT=3013
MEETING_SERVICE_PORT=3014
STREAM_SERVICE_PORT=3015
NOTIFICATION_SERVICE_PORT=3016
PRESENCE_SERVICE_PORT=3017
MEDIA_SERVICE_PORT=3018
ANALYTICS_SERVICE_PORT=3019
MODERATION_SERVICE_PORT=3020
SIGNALING_SERVER_PORT=3021
ENVEOF
    success "Created default .env file"
  fi
fi

# ── Step 4: Start infrastructure dependencies ───────────────────────────────
step "Starting infrastructure dependencies"

info "Pulling latest images..."
docker compose -f infrastructure/docker/docker-compose.deps.yml pull --quiet 2>/dev/null || true

info "Starting containers..."
docker compose -f infrastructure/docker/docker-compose.deps.yml up -d

success "Infrastructure containers started"

# ── Step 5: Wait for services to be healthy ──────────────────────────────────
step "Waiting for services to be healthy"

wait_for_healthy() {
  local container_name="$1"
  local max_attempts="${2:-30}"
  local attempt=0

  while [ $attempt -lt $max_attempts ]; do
    STATUS=$(docker inspect --format='{{.State.Health.Status}}' "${container_name}" 2>/dev/null || echo "not_found")
    case "${STATUS}" in
      healthy)
        success "${container_name} is healthy"
        return 0
        ;;
      not_found)
        warn "${container_name} container not found - skipping"
        return 0
        ;;
      *)
        attempt=$((attempt + 1))
        if [ $((attempt % 5)) -eq 0 ]; then
          info "${container_name}: ${STATUS} (attempt ${attempt}/${max_attempts})"
        fi
        sleep 2
        ;;
    esac
  done

  error "${container_name} did not become healthy within $((max_attempts * 2))s"
  return 1
}

HEALTHY=true
wait_for_healthy "rajutechie-streamkit-postgres" 30   || HEALTHY=false
wait_for_healthy "rajutechie-streamkit-redis"    15   || HEALTHY=false
wait_for_healthy "rajutechie-streamkit-mongodb"  30   || HEALTHY=false
wait_for_healthy "rajutechie-streamkit-kafka"    40   || HEALTHY=false
wait_for_healthy "rajutechie-streamkit-minio"    20   || HEALTHY=false

if [ "${HEALTHY}" = false ]; then
  warn "Some services did not become healthy - check 'docker compose -f infrastructure/docker/docker-compose.deps.yml logs'"
fi

# ── Step 6: Database migrations ─────────────────────────────────────────────
step "Running database migrations"

if pnpm run db:migrate 2>/dev/null; then
  success "Database migrations completed"
else
  info "No migrations configured yet - skipping (run 'pnpm db:migrate' when ready)"
fi

# ── Step 7: Seed development data ───────────────────────────────────────────
step "Seeding development data"

if pnpm run db:seed 2>/dev/null; then
  success "Development data seeded"
else
  info "No seed scripts configured yet - skipping (run 'pnpm db:seed' when ready)"
fi

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║         Setup completed successfully!         ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BOLD}Infrastructure URLs:${NC}"
echo -e "  PostgreSQL:      localhost:${POSTGRES_PORT:-5432}"
echo -e "  MongoDB:         localhost:${MONGODB_PORT:-27017}"
echo -e "  Redis:           localhost:${REDIS_PORT:-6379}"
echo -e "  Kafka:           localhost:${KAFKA_PORT:-9092}"
echo -e "  MinIO API:       http://localhost:${MINIO_API_PORT:-9000}"
echo -e "  MinIO Console:   http://localhost:${MINIO_CONSOLE_PORT:-9001}"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo -e "  ${CYAN}pnpm dev${NC}              Start all services in dev mode"
echo -e "  ${CYAN}pnpm build${NC}            Build all packages"
echo -e "  ${CYAN}pnpm test${NC}             Run all tests"
echo -e "  ${CYAN}pnpm lint${NC}             Lint the codebase"
echo -e "  ${CYAN}pnpm docker:deps:down${NC} Stop infrastructure containers"
echo ""
echo -e "  To seed sample data:  ${CYAN}./tools/scripts/seed-db.sh${NC}"
echo -e "  To generate types:    ${CYAN}./tools/scripts/generate-proto.sh${NC}"
echo ""
