apiVersion: v1
kind: ConfigMap
metadata:
  name: rajutechie-streamkit-config
  namespace: rajutechie-streamkit
  labels:
    app.kubernetes.io/name: rajutechie-streamkit
    app.kubernetes.io/part-of: rajutechie-streamkit-platform
data:
  NODE_ENV: production
  LOG_LEVEL: info
  REDIS_URL: "redis://redis:6379"
  KAFKA_BROKERS: "kafka:9092"
  DATABASE_URL: "postgresql://rajutechie-streamkit:rajutechie-streamkit@postgres:5432/rajutechie-streamkit"
  MONGODB_URI: "mongodb://mongo:27017/rajutechie-streamkit"
