apiVersion: v1
kind: Namespace
metadata:
  name: rajutechie-streamkit
  labels:
    app.kubernetes.io/name: rajutechie-streamkit
    app.kubernetes.io/part-of: rajutechie-streamkit-platform
    app.kubernetes.io/managed-by: kustomize
