apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "rajutechie-streamkit.namespace" . }}
  labels:
    {{- include "rajutechie-streamkit.labels" (dict "serviceName" "rajutechie-streamkit" "context" $) | nindent 4 }}
